name: 'Get Daily BingPic'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.9        
      
      - name: 'Install dependencies'
        run: python3 -m pip install --upgrade pip   
      
      - name: 'Install requirements'
        run: pip install -r ./requirements.txt 
      
      - name: 'RUN' 
        run: python bing.py 
      
      - name: Commit files
        run: |
          title=$(cat ./title)
          rm -vf ./title
          echo $title
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "$title" -a -a || echo "Nothing to commit"
      
      - name: 'Push changes'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
